actu_article:
    resource: "@ActuArticleBundle/Resources/config/routing.yml"
    prefix:   /articles

home:
    resource: "@HomeBundle/Resources/config/routing.yml"
    prefix:   /

# my:
#     resource: "@MyBundle/Resources/config/routing.yml"
#     prefix:   /

# app:
    # resource: '@AppBundle/Controller/'
    # type: annotation
