services:
#    actu_article.example:
#        class: Actu\ArticleBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]


  # ArticleBundle\DataFixtures\:
  #   resource: '../../DataFixtures'
  #   tags: ['doctrine.fixture.orm']